import { Book } from "./types";

export const books: Book[] = [
  {
    id: "1",
    title: "Atomic Habits",
    author: "James Clear",
    cover: "/atomichabits.jpg",
    description: "Tiny changes, remarkable results...",
    genre: ["Self-help"],
    rating: 4.8,
    pages: 320,
  },
  {
    id: "2",
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    cover: "/The_Great_Gatsby_Cover_1925_Retouched.jpg",
    description: "A classic American novel...",
    genre: ["Fiction"],
    rating: 4.5,
    pages: 180,
  },
  {
    id: "3",
    title: "Sapiens: A Brief History of Humankind",
    author: "Yuval Noah Harari",
    cover: "/sapiens.jpg",
    description: "A brief history of humankind...",
    genre: ["History"],
    rating: 4.7,
    pages: 443,
  },
  {
    id: "4",
    title: "1984",
    author: "George Orwell",
    cover: "/1984.jpg",
    description: "A dystopian social science fiction novel...",
    genre: ["Fiction"],
    rating: 4.6,
    pages: 328,
  },
  {
    id: "5",
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    cover: "/tokillamockingbird.jpg",
    description: "A gripping tale of racial injustice and childhood innocence...",
    genre: ["Fiction"],
    rating: 4.8,
    pages: 281,
  },
  {
    id: "6",
    title: "The Power of Habit",
    author: "James Clear",
    cover: "/thepowerofhabit.jpg",
    description: "An easy-to-understand guide to building good habits...",
    genre: ["Self-help"],
    rating: 4.7,
    pages: 320,
  },
  {
    id: "7",
    title: "The Catcher in the Rye",
    author: "J.D. Salinger",
    cover: "/thecatcherintherye.jpg",
    description: "A classic coming-of-age novel...",
    genre: ["Fiction"],
    rating: 4.5,
    pages: 277,
  },
  {
    id: "8",
    title: "The Subtle Art of Not Giving a F*ck",
    author: "Mark Manson",
    cover: "/thesubtleartofnotgivingafck.jpg",
    description: "A counterintuitive approach to living a good life...",
    genre: ["Self-help"],
    rating: 4.7,
    pages: 288,
  },
  {
    id: "9",
    title: "The Alchemist",
    author: "Paulo Coelho",
    cover: "/thealchemist.jpg",
    description: "A novel about a young shepherd boy who travels from his homeland in Spain to the Egyptian desert in search of a worldly treasure...",
    genre: ["Fiction"],
    rating: 4.6,
    pages: 163,
  },
  {
    id: "10",
    title: "Thinking, Fast and Slow",
    author: "Daniel Kahneman",
    cover: "/thinkingfastandslow.jpg",
    description: "A book about the two systems that drive the way we think...",
    genre: ["Psychology"],
    rating: 4.8,
    pages: 512,
  }

];