import { Book } from "./types";

export const books: Book[] = [
  {
    id: "1",
    title: "Atomic Habits",
    author: "James Clear",
    cover: "/atomichabits.jpg",
    description: "Tiny changes, remarkable results...",
    genre: ["Self-help"],
    rating: 4.8,
    pages: 320,
  },
  {
    id: "2",
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    cover: "/The_Great_Gatsby_Cover_1925_Retouched.jpg",
    description: "A classic American novel...",
    genre: ["Fiction"],
    rating: 4.5,
    pages: 180,
  },
  {
    id: "3",
    title: "Sapiens: A Brief History of Humankind",
    author: "Yuval Noah Harari",
    cover: "/sapiens.jpg",
    description: "A brief history of humankind...",
    genre: ["History"],
    rating: 4.7,
    pages: 443,
  },
  {
    id: "4",
    title: "1984",
    author: "George Orwell",
    cover: "/1984.jpg",
    description: "A dystopian social science fiction novel...",
    genre: ["Fiction"],
    rating: 4.6,
    pages: 328,
  },
  {
    id: "5",
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    cover: "/tokillamockingbird.jpg",
    description: "A gripping tale of racial injustice and childhood innocence...",
    genre: ["Fiction"],
    rating: 4.8,
    pages: 281,
  },
  {
    id: "6",
    title: "The Power of Habit",
    author: "James Clear",
    cover: "/thepowerofhabit.jpg",
    description: "An easy-to-understand guide to building good habits...",
    genre: ["Self-help"],
    rating: 4.7,
    pages: 320,
  },
  {
    id: "7",
    title: "The Catcher in the Rye",
    author: "J.D. Salinger",
    cover: "/thecatcherintherye.jpg",
    description: "A classic coming-of-age novel...",
    genre: ["Fiction"],
    rating: 4.5,
    pages: 277,
  },
  {
    id: "8",
    title: "The Subtle Art of Not Giving a F*ck",
    author: "Mark Manson",
    cover: "/thesubtleartofnotgivingafck.jpg",
    description: "A counterintuitive approach to living a good life...",
    genre: ["Self-help"],
    rating: 4.7,
    pages: 288,
  },
  {
    id: "9",
    title: "The Alchemist",
    author: "Paulo Coelho",
    cover: "/thealchemist.jpg",
    description: "A novel about a young shepherd boy who travels from his homeland in Spain to the Egyptian desert in search of a worldly treasure...",
    genre: ["Fiction"],
    rating: 4.6,
    pages: 163,
  },
  {
    id: "10",
    title: "Thinking, Fast and Slow",
    author: "Daniel Kahneman",
    cover: "/thinkingfastandslow.jpg",
    description: "A book about the two systems that drive the way we think...",
    genre: ["Psychology"],
    rating: 4.8,
    pages: 512,
  },
  {
    id: "11",
    title: "The 7 Habits of Highly Effective People",
    author: "Stephen R. Covey",
    cover: "/the7habits.jpg",
    description: "A guide to personal and professional effectiveness...",
    genre: ["Self-help"],
    rating: 4.7,
    pages: 368,
  },
  {
    id: "12",
    title: "The Lord of the Rings",
    author: "J.R.R. Tolkein",
    cover: "/thelordoftherings.jpg",
    description: "A high fantasy novel...",
    genre: ["Fantasy"],
    rating: 4.9,
    pages: 1216,
  },
  {
    id: "13",
    title: "Harry Potter and the Philosopher's Stone",
    author: "J.K. Rowling",
    cover: "/harrypotter.jpg",
    description: "The first book in the Harry Potter series...",
    genre: ["Fantasy"],
    rating: 4.8,
    pages: 309,
  },
  //add history, psychology, science, programming, technology and more self-help books to make it 100 books in total
  {
    id: "14",
    title: "The Lean Startup",
    author: "Eric Ries",
    cover: "/theleanstartup.jpg",
    description: "A systematic approach to building and scaling a startup...",
    genre: ["Business"],
    rating: 4.6,
    pages: 320,

  },
  {
    id: "15",
    title: "The Art of War",
    author: "Sun Tzu",
    cover: "/theartofwar.jpg",
    description: "A classic military treatise...",
    genre: ["History"],
    rating: 4.8,
    pages: 208,
  },
  {
    id: "16",
    title: "The Design of Everyday Things",
    author: "Don Norman",
    cover: "/thedesignofeverydaythings.jpg",
    description: "A classic book on design and usability...",
    genre: ["Design"],
    rating: 4.7,
    pages: 368,
  },
    {
    id: "17",
    title: "The Innovator's Dilemma",
    author: "Clayton M. Christensen",
    cover: "/theinnovatorsdilemma.jpg",
    description: "A book about disruptive innovation and how companies can avoid it...",
    genre: ["Business"],
    rating: 4.6,
    pages: 288,
    },
    {
    id: "18",
    title: "The Power of Now",
    author: "Eckhart Tolle",
    cover: "/thepowerofnow.jpg",
    description: "A guide to living in the present moment...",
    genre: ["Self-help"],
    rating: 4.7,
    pages: 288,
  },
  {
    id: "19",
    title: "The Art of Happiness",
    author: "Dalai Lama",
    cover: "/theartofhappiness.jpg",
    description: "A guide to finding happiness and fulfillment...",
    genre: ["Self-help"],
    rating: 4.6,
    pages: 288,
  },
  {
    id: "20",
    title: "The 4-Hour Workweek",
    author: "Tim Ferriss",
    cover: "/the4hourworkweek.jpg",
    description: "A guide to lifestyle design and productivity...",
    genre: ["Self-help"],
    rating: 4.6,
    pages: 320,
  }
];